theme: jekyll-theme-cayman
name: Prashant Tatineni
title: Prashant Tatineni
description: Data Scientist at Metis


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-90744512-1

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/14060620?v=3&u=471332a73def3a3426f4ed35bdd428bc83159d1f&s=400
